# Generated by Django 2.2 on 2021-05-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
