# Generated by Django 2.2 on 2021-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210511_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_study_mode',
            field=models.CharField(default='1,1,1,1', max_length=20, verbose_name='用户学习模式'),
        ),
    ]
