# Generated by Django 2.2 on 2021-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210608_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='question_difficulty',
            field=models.IntegerField(default=0, verbose_name='题目难度'),
        ),
    ]
