# Generated by Django 2.2 on 2021-06-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210610_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement_title',
            field=models.CharField(default='', max_length=100, verbose_name='成就'),
        ),
    ]
