# Generated by Django 2.2 on 2021-06-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_diamond'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_num',
            field=models.IntegerField(default=0, verbose_name='组别'),
        ),
    ]
