# Generated by Django 2.2 on 2021-06-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_group_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group_num',
        ),
    ]
