# Generated by Django 2.2 on 2021-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_group_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stay_methodPage_time',
            field=models.IntegerField(default=0, verbose_name='页面时长'),
        ),
    ]
