# Generated by Django 2.2 on 2021-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_stay_methodpage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diamond_pieces',
            field=models.IntegerField(default=0, verbose_name='宝石碎片'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lottery_model',
            field=models.CharField(default='', max_length=100, verbose_name='抽奖模型'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade_class',
            field=models.CharField(default='暂无', max_length=20, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='暂无', max_length=20, verbose_name='昵称'),
        ),
    ]
