# Generated by Django 2.2 on 2021-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210701_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lottery_model',
            field=models.CharField(default='', max_length=200, verbose_name='抽奖模型'),
        ),
    ]
